export const COUNTRY_CODES = [
  { code: "+93", country: "Afghanistan", iso: "AF" },
  { code: "+355", country: "Albania", iso: "AL" },
  { code: "+213", country: "Algeria", iso: "DZ" },
  { code: "+376", country: "Andorra", iso: "AD" },
  { code: "+244", country: "Angola", iso: "AO" },
  { code: "+54", country: "Argentina", iso: "AR" },
  { code: "+374", country: "Armenia", iso: "AM" },
  { code: "+61", country: "Australia", iso: "AU" },
  { code: "+43", country: "Austria", iso: "AT" },
  { code: "+994", country: "Azerbaijan", iso: "AZ" },

  { code: "+973", country: "Bahrain", iso: "BH" },
  { code: "+880", country: "Bangladesh", iso: "BD" },
  { code: "+375", country: "Belarus", iso: "BY" },
  { code: "+32", country: "Belgium", iso: "BE" },
  { code: "+501", country: "Belize", iso: "BZ" },
  { code: "+229", country: "Benin", iso: "BJ" },
  { code: "+975", country: "Bhutan", iso: "BT" },
  { code: "+591", country: "Bolivia", iso: "BO" },
  { code: "+387", country: "Bosnia & Herzegovina", iso: "BA" },
  { code: "+267", country: "Botswana", iso: "BW" },
  { code: "+55", country: "Brazil", iso: "BR" },
  { code: "+673", country: "Brunei", iso: "BN" },
  { code: "+359", country: "Bulgaria", iso: "BG" },

  { code: "+855", country: "Cambodia", iso: "KH" },
  { code: "+237", country: "Cameroon", iso: "CM" },
  { code: "+1", country: "Canada", iso: "CA" },
  { code: "+238", country: "Cape Verde", iso: "CV" },
  { code: "+236", country: "Central African Republic", iso: "CF" },
  { code: "+235", country: "Chad", iso: "TD" },
  { code: "+56", country: "Chile", iso: "CL" },
  { code: "+86", country: "China", iso: "CN" },
  { code: "+57", country: "Colombia", iso: "CO" },
  { code: "+269", country: "Comoros", iso: "KM" },
  { code: "+242", country: "Congo", iso: "CG" },
  { code: "+506", country: "Costa Rica", iso: "CR" },
  { code: "+385", country: "Croatia", iso: "HR" },
  { code: "+53", country: "Cuba", iso: "CU" },
  { code: "+357", country: "Cyprus", iso: "CY" },
  { code: "+420", country: "Czech Republic", iso: "CZ" },

  { code: "+45", country: "Denmark", iso: "DK" },
  { code: "+253", country: "Djibouti", iso: "DJ" },
  { code: "+20", country: "Egypt", iso: "EG" },
  { code: "+503", country: "El Salvador", iso: "SV" },
  { code: "+372", country: "Estonia", iso: "EE" },
  { code: "+251", country: "Ethiopia", iso: "ET" },

  { code: "+358", country: "Finland", iso: "FI" },
  { code: "+33", country: "France", iso: "FR" },

  { code: "+995", country: "Georgia", iso: "GE" },
  { code: "+49", country: "Germany", iso: "DE" },
  { code: "+233", country: "Ghana", iso: "GH" },
  { code: "+30", country: "Greece", iso: "GR" },
  { code: "+502", country: "Guatemala", iso: "GT" },

  { code: "+852", country: "Hong Kong", iso: "HK" },
  { code: "+36", country: "Hungary", iso: "HU" },

  { code: "+354", country: "Iceland", iso: "IS" },
  { code: "+91", country: "India", iso: "IN" },
  { code: "+62", country: "Indonesia", iso: "ID" },
  { code: "+98", country: "Iran", iso: "IR" },
  { code: "+964", country: "Iraq", iso: "IQ" },
  { code: "+353", country: "Ireland", iso: "IE" },
  { code: "+972", country: "Israel", iso: "IL" },
  { code: "+39", country: "Italy", iso: "IT" },

  { code: "+81", country: "Japan", iso: "JP" },
  { code: "+962", country: "Jordan", iso: "JO" },

  { code: "+254", country: "Kenya", iso: "KE" },
  { code: "+965", country: "Kuwait", iso: "KW" },
  { code: "+996", country: "Kyrgyzstan", iso: "KG" },

  { code: "+856", country: "Laos", iso: "LA" },
  { code: "+371", country: "Latvia", iso: "LV" },
  { code: "+961", country: "Lebanon", iso: "LB" },
  { code: "+370", country: "Lithuania", iso: "LT" },
  { code: "+352", country: "Luxembourg", iso: "LU" },

  { code: "+60", country: "Malaysia", iso: "MY" },
  { code: "+960", country: "Maldives", iso: "MV" },
  { code: "+356", country: "Malta", iso: "MT" },
  { code: "+52", country: "Mexico", iso: "MX" },
  { code: "+377", country: "Monaco", iso: "MC" },
  { code: "+976", country: "Mongolia", iso: "MN" },
  { code: "+212", country: "Morocco", iso: "MA" },

  { code: "+31", country: "Netherlands", iso: "NL" },
  { code: "+64", country: "New Zealand", iso: "NZ" },
  { code: "+234", country: "Nigeria", iso: "NG" },
  { code: "+47", country: "Norway", iso: "NO" },

  { code: "+92", country: "Pakistan", iso: "PK" },
  { code: "+63", country: "Philippines", iso: "PH" },
  { code: "+48", country: "Poland", iso: "PL" },
  { code: "+351", country: "Portugal", iso: "PT" },

  { code: "+974", country: "Qatar", iso: "QA" },

  { code: "+40", country: "Romania", iso: "RO" },
  { code: "+7", country: "Russia", iso: "RU" },

  { code: "+966", country: "Saudi Arabia", iso: "SA" },
  { code: "+65", country: "Singapore", iso: "SG" },
  { code: "+27", country: "South Africa", iso: "ZA" },
  { code: "+82", country: "South Korea", iso: "KR" },
  { code: "+34", country: "Spain", iso: "ES" },
  { code: "+94", country: "Sri Lanka", iso: "LK" },
  { code: "+46", country: "Sweden", iso: "SE" },
  { code: "+41", country: "Switzerland", iso: "CH" },

  { code: "+886", country: "Taiwan", iso: "TW" },
  { code: "+66", country: "Thailand", iso: "TH" },
  { code: "+90", country: "Turkey", iso: "TR" },

  { code: "+971", country: "UAE", iso: "AE" },
  { code: "+44", country: "United Kingdom", iso: "GB" },
  { code: "+1", country: "United States", iso: "US" },
  { code: "+998", country: "Uzbekistan", iso: "UZ" },

  { code: "+58", country: "Venezuela", iso: "VE" },
  { code: "+84", country: "Vietnam", iso: "VN" },

  { code: "+263", country: "Zimbabwe", iso: "ZW" },
];
